services:
  static_hosting:
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8091:80

  backend:
    image: couchdb
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    healthcheck:
      test: curl -f http://localhost:5984/_up || exit 1
      interval: 2s
      timeout: 3s

  accessible_backend:
    image: curlimages/curl
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        alias put="curl -X PUT -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'"
        put backend:5984/_node/nonode@nohost/_config/chttpd/enable_cors --data '"true"'
        put backend:5984/_node/nonode@nohost/_config/cors/origins --data '"*"'
        put backend:5984/blutt
        put backend:5984/blutt/_security --data '{"members":{"roles":[]},"admins":{"roles":["_admin"]}}'
    depends_on:
      backend:
        condition: service_healthy

  updated_samples:
    image: curlimages/curl
    entrypoint: [ "/bin/sh","-c" ]
    volumes:
      - ./frontend/public:/public
    command:
      - |
        curl -X POST http://backend:5984/blutt/_bulk_docs -H "Content-Type: application/json" -d @/public/sample_data.json
    depends_on:
      accessible_backend:
        condition: service_completed_successfully

  index:
    image: curlimages/curl
    entrypoint: [ "/bin/sh","-c" ]
    volumes:
      - ./backend/by_date.json:/by_date.json
    command:
      - |
        curl -X POST http://backend:5984/qvotidie/_index -H "Content-Type: application/json" -d @/by_date.json -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'
    depends_on:
      accessible_backend:
        condition: service_completed_successfully